version: 2
jobs:
  build:
    working_directory: ~/stac
    docker:
      - image: circleci/python:3.6.9

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: install
          command: |
            pip install stac-validator
            sudo apt-get install curl software-properties-common
            curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g remark-cli remark-validate-links
      - run:
          name: validate
          command: |
            stac_validator catalog-spec/examples/catalog.json
            stac_validator collection-spec/examples/sentinel2.json
            stac_validator item-spec/examples/sample.json
            stac_validator item-spec/examples/sample-full.json
            stac_validator item-spec/examples/sentinel2-sample.json
            stac_validator item-spec/examples/planet-sample.json
            stac_validator item-spec/examples/landsat8-sample.json
            stac_validator item-spec/examples/digitalglobe-sample.json
            stac_validator item-spec/examples/CBERS_4_MUX_20181029_177_106_L4.json
            remark -u validate-links .