version: 2
jobs:
  build:
    working_directory: ~/stac
    docker:
      - image: danvk/yarn-python36:0.0.1

    steps:
      - checkout
      - run:
          name: install
          command: |
            python3.6 -m venv venv
            . venv/bin/activate
            pip install stac-validator
            npm install remark-cli remark-validate-links
      - run:
          name: validate
          command: |
            . venv/bin/activate
            stac_validator catalog-spec/examples/catalog.json
            stac_validator collection-spec/examples/sentinel2.json
            stac_validator item-spec/examples/sample.json
            stac_validator item-spec/examples/sample-full.json
            stac_validator item-spec/examples/sentinel2-sample.json
            stac_validator item-spec/examples/planet-sample.json
            stac_validator item-spec/examples/landsat8-sample.json
            stac_validator item-spec/examples/digitalglobe-sample.json
            stac_validator item-spec/examples/CBERS_4_MUX_20181029_177_106_L4.json
            remark -u validate-links .
